security:
  user:
    password: password
  ignored:
  - "*.bundle.*"
spring:
  session:
    store-type: redis
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
      sensitive-headers:
